version: "3.8"

services:
  admin-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: admin_backend
    ports:
      - "8100:8100"
    environment:
      - AWS_REGION
      - BUCKET_NAME
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
  admin-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: admin_frontend
    ports:
      - "3001:80"
    depends_on:
      - admin-backend
